### ISSUE TITLE
`const ${localName(method)}` can result in a not allowed variable name

### ISSUE THREAD

**Issue by Madumo** [bufbuild/connect-query#18]
I have a case where a service has a "Delete" method. Since the generator will output `export const ${localName(method)} = ...`, it will output `export const delete = ...`, which is a reserved keyword in javascript and cannot be used as a variable name in strict mode. This will make typescript compilation fail with no way of ignoring the issue.

While "delete" is the more likely case to happen in this context, all methods named after a [reserved word](https://www.w3schools.com/js/js_reserved.asp) will also generate invalid code as such.

A simple solution could be using PascalCase for the variable declaration, but that would also break any code using this after the upgrade.

What are your thought on this? 

In the meantime i'll just automatically patch the file after generation with a sed command.

Thanks a lot by the way, this toolchain is a game changer for us compared to using grpc-web! :)

**Comment by dimitropoulos** [comment]
You're totally right.  This is a problem.

I've added a PR for one solution to this in #19.  Would love to hear your feedback on the approach taken.

p.s. thanks for the kind words!
