### ISSUE TITLE
How to set `QueryObserverOptions`?

### ISSUE THREAD

**Issue by cherewaty** [bufbuild/connect-query#30]
I end up customizing `refetchInterval` per query pretty often with Tanstack Query's `useQuery`. On some pages, I want rapid 1-second polls of a specific unary call, and on others just once a minute or so.

Is there a mechanism for setting any of the `QueryObserverOptions`, like `refetchInterval`,  with a `useQuery` generated from `@bufbuild/connect-query`?

This doesn't appear to work at the moment, but should the full array of Tanstack Query's `useQuery` options (https://tanstack.com/query/v4/docs/react/reference/useQuery) be available to `UnaryHooks.useQuery.options`?
```
const { data: things } = useQuery(getThings.useQuery({}, { refetchInterval: 1000 }));
```

**Comment by cherewaty** [comment]
I applied the documented pattern, and it's working great. Thanks for the FAQ addition!

**Comment by dimitropoulos** [comment]
that's great!  let us know how you like connect-query and if there's anything you'd like it to do better! the [Buf Slack](https://buf.build/docs/contact/) is a great place to informally drop us a line!
