### ISSUE TITLE
Export ESM format

### ISSUE THREAD

**Issue by treelite** [bufbuild/connect-query#54]
Hey there! Wondering have you consider to compile and export esm format like other `@bufuild` packages did?

Currently I'm using both `connect-query` and `connect-web`, noticed seems there is one bundle size impact due to the different export format(`cjs`) `connect-query` is using:
![Screenshot 2023-06-30 at 1 03 49 pm](https://github.com/bufbuild/connect-query/assets/1505477/4a67f910-fe33-466b-a889-bf8e7c4df264)

Using Webpack 5, some functions in `@bufbuild/protobuf` and `@bufbuild/connect` were bundled twice. All `conect-query`'s dependences will be imported from `cjs` and the same function used in my source code via `import` will be imported from `esm`. 

Ran a quick local test, added `esm` to `connect-query` and got this:
![Screenshot 2023-06-30 at 1 10 48 pm](https://github.com/bufbuild/connect-query/assets/1505477/57049059-3245-407e-8df0-4f46a64e58e0)

Would be good to do so? Thank you :)

**Comment by paul-sachs** [comment]
@treelite will take a look and see what can be done. It does look like we're not labeling the package as a module so bundlers may grab the cjs for dependencies. Which version of connect-query are you using?

**Comment by treelite** [comment]
Thank you for the quick reponse @paul-sachs , I'm using the `0.2.3`. Just had a quick test, your PR looks good, no cjs files in the final bundle 👍

**Comment by paul-sachs** [comment]
🚀 Released in v0.4.0
